# Generated by Django 5.2.3 on 2025-10-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('work_status', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], max_length=20, null=True)),
                ('total_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('total_experience_months', models.PositiveIntegerField(blank=True, null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
