# Generated by Django 5.2.3 on 2025-08-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('file', models.FileField(upload_to='templates/html/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
