# Generated by Django 5.2.3 on 2025-09-16 15:33

import templateapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='file',
            field=models.FileField(upload_to='template_files/', validators=[templateapp.models.validate_html_file]),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/'),
        ),
    ]
