# Generated by Django 5.2.3 on 2025-10-05 10:02

import cltemplateapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='cover_letter_previews/')),
                ('file', models.FileField(upload_to='cover_letter_files/', validators=[cltemplateapp.models.validate_html_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
