# Generated by Django 5.2.3 on 2025-10-05 10:20

import cltemplateapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltemplateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverlettertemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cover_letter_files/', validators=[cltemplateapp.models.validate_html_file]),
        ),
    ]
