# Generated by Django 5.2.3 on 2025-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='personal_images/'),
        ),
    ]
